config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
      resources :users, only: [:new, :create], path: '/register', path_names: {new: '/'}
      resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: {new: '/'}
  end  
  
  resources :favorites, only: [:index, :create, :destroy], param: :product_id 
  resources :users, only: :show, path:'/user', param: :username #cambiamos el id por el username
  resources :categories, except: :show
  resources :products, path:'/'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #  Defines the root path route ("/")
  #   root "articles#index"
  # delete '/products/:id', to: 'products#destroy'
  # patch '/products/:id', to: 'products#update'
  # post '/products', to: 'products#create'
  # get '/products/new', to:'products#new', as: :new_product
  # get '/products', to:'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product


end

app/views/shared/_flash.html.erb
 <%= notice%>
 
 <%= alert %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
   <h1><%= t('app_name') %></h1>
<% end %>
<%
=begin%>
 <%= Current.user.inspect %>> 
<%
=end%>
<div><%= button_to link_to t('.login'), new_session_path unless Current.user %><br>
<%= button_to link_to t('.register'), new_user_path unless Current.user %></div><br>
<%= button_to link_to t('.favorites'), favorites_path if Current.user %></div><br>
<%= button_to link_to t('.add'), new_product_path if Current.user  %><br>
<%= button_to link_to t('.categories') , categories_path if Current.user&.admin? %><br>
<%= button_to link_to t('.logout'), session_path(Current.user.id),
    data:{ 
         turbo_method: :delete,
         turbo_confirm: t('common.confirm')
       } if Current.user %></div><br>

 