config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
      resources :users, only: [:new, :create], path: '/register', path_names: {new: '/'}
      resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: {new: '/'}
  end  
  
  resources :favorites, only: [:index, :create, :destroy], param: :product_id 
  resources :users, only: :show, path:'/user', param: :username #cambiamos el id por el username
  resources :categories, except: :show
  resources :products, path:'/'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #  Defines the root path route ("/")
  #   root "articles#index"
  # delete '/products/:id', to: 'products#destroy'
  # patch '/products/:id', to: 'products#update'
  # post '/products', to: 'products#create'
  # get '/products/new', to:'products#new', as: :new_product
  # get '/products', to:'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product


end

app/models/product.rb
class Product < ApplicationRecord
     include PgSearch::Model
     include Favoritable
     pg_search_scope :search_full_text, against: {
         title: 'A',
         description: 'B'
       }

    ORDER_BY = { 
       newest: "created_at DESC",
       expensive: "price DESC",
       cheapest: "price ASC"
      }
    has_one_attached :photo

    validates :title, presence: true
    validates :description, presence:true
    validates :price, presence:true 
    

    belongs_to :category
    belongs_to :user, default: ->  { Current.user } #O realizarlo deade products_controller
    
    def owner
      user_id == Current.user&.id
    end
    
 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :protect_pages, only: [:index, :show]
  def index
   @categories = Category.order(name: :asc).load_async
   @pagy , @products= pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 8)

   #Refactorizamos el codigo en find_products.rb
    
   #@products = Product.with_attached_photo
    #   order_by= Product::ORDER_BY.fetch(params[:order_by]&.to_sym, Product::ORDER_BY[:newest])
    #   @products = @products.order(order_by) 

    # if params[:category_id]
    #  @products = @products.where(category_id: params[:category_id])
    # end

    # if params[:min_price].present?
    #   @products = @products.where("price >= ?", params[:min_price])
    # end

    # if params[:max_price].present?
    #   @products = @products.where("price <= ?", params[:max_price])
    # end
    # order_by= Product::ORDER_BY.fetch(params[:order_by]&.to_sym, Product::ORDER_BY[:newest])
    # @products = @products.order(order_by) 
   # @pagy, @products = pagy_countless(@products, items:5)
  #  if params[:query_text].present?
  #     @products = @products.search_full_text(params[:query_text]) #( la query del text me sale en la url, segun el metodo post, pero se la carga en la busqueda)
  #  end
    
    
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    # @product = Current.user.products.new(product_params) (Una manera haciendo scopeding)
    @product = Product.new(product_params)
    # pp @product
    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize! product    
  end

  def update
    authorize! product
    if product.update (product_params)
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! product
    product.destroy
    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end


  private

  def product_params
     params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end

  def product_params_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites)
  end
  
  def product
    @product = Product.find(params[:id])
  end

end

app/views/products/_category.html.erb
<%=link_to products_path(category_id: category.id),class: 'category' do %>
    <%= category.name %>
<%end %>

app/views/products/_form.html.erb
<%= form_with model: @product do | form| %>
 <% @product.errors.full_messages.each do |error| %>
   <div>
        <%= error %>
   </div>
 <% end %>
 <div>
   <%= form.label :title %>
   <%= form.text_field :title  %> 
 </div>
 <div>
   <%= form.label :category_id %>
   <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
 </div>

 <div>
   <%= form.label :description  %>
   <%= form.text_area :description %>
  </div> 
 <div>
   <%= form.label :price %>
   <%= form.number_field :price %>
 </div>
  <div>
   <%= form.label :photo %>
   <%= form.file_field :photo %>
 </div>

 <%= form.submit %> 
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product), class: 'product', 'data-turbo-frame': '_top' do %>
     <p><strong>Modelo:</strong> <%= product.title %></p>
     <%= image_tag product.photo, width:100 if product.photo.attached?%><br>&rarr;
     <span><%= product.price %>€</span>
<% end %><hr>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>
    <h2><%= t('.title') %></h2> 
    <%= link_to t('.all'), products_path %>
    <%= render partial: 'category', collection: @categories %><br> 
    <%= form_with url: products_path, method: :get do |form| %>
      <%=form.text_field :query_text, placeholder: t('.query_text'),
       onChange: 'this.form.requestSubmit()', value: params[:query_text]%>
      <%=form.number_field :min_price, placeholder: t('.min_price'),
       onChange: 'this.form.requestSubmit()', value: params[:min_price]%>
      <%=form.number_field :max_price, placeholder: t('.max_price'),
       onChange: 'this.form.requestSubmit()', value: params[:max_price]%>
      <%=form.select :order_by, options_for_select(Product::ORDER_BY.keys.map{|order|[t(".#{order}"), order]}, params[:order_by]),{},
      { onChange: 'this.form.requestSubmit()'} %> 
      <% end %>
    <div>Total:
        <%= @products.count %> <%= t('.title_1') %>
    </div>
    <div>Fecha<%= Date.today %></div>
    <div class="products">
    <%= render partial: 'product', collection: @products %>
    </div>

    <%=turbo_frame_tag :products do %>
      <%=turbo_frame_tag "products-#{@pagy.page}", class: "product" do %>
        <%= render partial: 'product', collection: @products %>
        <%= turbo_frame_tag "products-#{@pagy.next}", class: "product", src: pagy_url_for(@pagy, @pagy.next),
            loading: :lazy  if @pagy.next %>
       <%end %> 
    <%end %> 
<% end %>

app/views/products/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/show.html.erb
<h1 class='title'><%= @product.title %></h1>
<%= image_tag @product.photo, width:200, height:200 if @product.photo.attached?%>

<p class='description'><%= @product.description %></p>

<span class='price'><%= @product.price %>€</span><br>

<%= button_to link_to t('.edit'), edit_product_path(@product) if @product.owner %><br>

<%= button_to link_to t('.delete'), product_path(@product),data:{ 
    turbo_method: :delete,
    turbo_confirm: t('common.confirm'),
 } if @product.owner %>

<%= button_to link_to t('.view_more_products', username: @product.user.username), user_path(@product.user.username) %>


<% if @product.favorite %>
    <%= button_to link_to '💔', favorite_path(@product.id ),data:{ 
        turbo_method: :delete  }  %>    

<% else %>
    <%= button_to link_to '💘', favorites_path(product_id: @product.id ),data:{ 
        turbo_method: :post  }  %>

<% end %>